spring:
  application:
    name: payment-service
  config:
    import: configserver:http://localhost:8888
  kafka:
    bootstrap-servers: localhost:29092

    consumer:
      group-id: "payment-group-id"
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        acks: 1
        spring:
          json:
            add:
              type:
                headers: false

  datasource:
    url: jdbc:postgresql://localhost:5433/db_payment
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 0

topic:
  send-payment: payment-request-topic
  send-payment-response: payment-response-topic
